services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://dodojota:0808@db:5432/weatherdata
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dodojota
      POSTGRES_PASSWORD: 0808
      POSTGRES_DB: weatherdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: